# Generated by Django 5.1.3 on 2025-05-06 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('occupation', models.CharField(max_length=50)),
                ('physical_activity', models.CharField(max_length=20)),
                ('sleep_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('quality_of_sleep', models.IntegerField(blank=True, null=True)),
                ('stress_level', models.CharField(blank=True, max_length=10, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('bp_category', models.CharField(blank=True, max_length=30, null=True)),
                ('systolic', models.PositiveIntegerField(blank=True, null=True)),
                ('diastolic', models.PositiveIntegerField(blank=True, null=True)),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('daily_steps', models.PositiveIntegerField(blank=True, null=True)),
                ('sleep_disorder', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
