# Generated by Django 5.1.3 on 2025-05-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinput',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinput',
            name='bmi_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
