# Generated by Django 5.1.3 on 2025-06-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fitnessdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessdata',
            name='weight_goal',
            field=models.IntegerField(max_length=255),
        ),
    ]
